version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes: 
      - ./data:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    volumes: 
      - ./data:/data/db
    ports:
      - '8081:8081'

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    command: python3 run.py
    depends_on:
      - mongo

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    command: python3 run.py
    depends_on:
      - mongo

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - '8080:80'
    volumes: 
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - mongo-express

  newman:
    container_name: newman
    image: postman/newman
    volumes:
      - ./tests:/etc/newman
    command: run /etc/newman/integration.json
    profiles:
      - testing
    depends_on:
      - nginx-proxy

