{
 "title": "Prometheus Flask exporter dashboard",
 "description": "Example dashboard for monitoring Flask webapps using prometheus_flask_exporter",
 "time": { "from": "2023-02-26T16:07:45.168Z", "to": "2023-02-26T16:10:02.250Z" },
 "panels": [
  {
   "title": "Requests rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\",instance=\"frontend:8080\", path!~\"/decks/[0-9]+/study\"}[60s])",
     "legendFormat": "{{ path }}"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/sessions/[0-9]*\"}[60s]))",
     "legendFormat": "/api/sessions/..."
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/sessions/[0-9]*/[0-9]*/yes\"}[60s]))",
     "legendFormat": "/api/sessions/.../yes"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/sessions/[0-9]*/[0-9]*/no\"}[30s]))",
     "legendFormat": "/api/sessions/.../no"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/decks/[0-9]+\"}[60s]))",
     "legendFormat": "/api/decks/..."
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/scores/[0-9]+\"}[60s]))",
     "legendFormat": "/api/scores/..."
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/cards/[0-9]+\"}[60s]))",
     "legendFormat": "/api/cards/..."
    },
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=\"/api/decks\"}[60s])",
     "legendFormat": "{{ path }}"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\",instance=\"frontend:8080\", path=~\"/decks/[0-9]+/study\"}[60s]))",
     "legendFormat": "/decks/.../study"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\",instance=\"frontend:8080\", path!~\"/decks/[0-9]+/study\"}[120s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\",instance=\"frontend:8080\", path!~\"/decks/[0-9]+/study\"}[120s])",
     "legendFormat": "{{ path }}"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\", instance=\"backend:8080\", path=~\"/api/sessions/[0-9]*\"}[5m])) / sum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/sessions/[0-9]*\"}[5m]))",
     "legendFormat": "/api/sessions/..."
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\", instance=\"backend:8080\", path=~\"/api/sessions/[0-9]*/[0-9]*/yes\"}[120s]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/sessions/[0-9]*/[0-9]*/yes\"}[120s]))",
     "legendFormat": "/api/sessions/.../yes"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\", instance=\"backend:8080\", path=~\"/api/sessions/[0-9]*/[0-9]*/no\"}[120s]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/sessions/[0-9]*/[0-9]*/no\"}[120s]))",
     "legendFormat": "/api/sessions/.../no"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\", instance=\"backend:8080\", path=~\"/api/decks/[0-9]+\"}[120s]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/decks/[0-9]+\"}[120s]))",
     "legendFormat": "/api/decks/..."
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\", instance=\"backend:8080\", path=~\"/api/scores/[0-9]+\"}[120s]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/scores/[0-9]+\"}[120s]))",
     "legendFormat": "/api/scores/..."
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\", instance=\"backend:8080\", path=~\"/api/cards/[0-9]+\"}[60s]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=~\"/api/cards/[0-9]+\"}[60s]))",
     "legendFormat": "/api/cards/..."
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\", instance=\"backend:8080\", path=\"/api/decks\"}[60s]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\", instance=\"backend:8080\", path=\"/api/decks\"}[60s]))",
     "legendFormat": "{{ path }}"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\",instance=\"frontend:8080\", path=~\"/decks/[0-9]+/study\"}[60s]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\",instance=\"frontend:8080\", path=~\"/decks/[0-9]+/study\"}[60s]))",
     "legendFormat": "/decks/.../study"
    }
   ]
  },
  {
   "title": "Yes / No answers distribution",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(count by (ans) (\n  label_replace(\n    flask_http_request_duration_seconds_count{instance=\"backend:8080\",path=~\"/api/sessions/[0-9]*/[0-9]*/(yes|no)\",status=\"200\"},\n    \"ans\",\n    \"$1\",\n    \"path\",\n    \"/api/sessions/[0-9]*/[0-9]*/(.+)\"\n  )\n)[5m:1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  }
 ]
}